name: 'Bolt Build Setup Steps'
description: 'Executes necessary commands to setup environment for the bolt build'
runs:
  using: "composite"
  steps:
    - name: Setup conan profile
      shell: bash
      run: |
        conan profile detect
        cat >> ~/.conan2/profiles/default <<EOF

        [conf]
        tools.build:exelinkflags=['-fuse-ld=mold', '-Wl,--allow-multiple-definition']
        tools.build:sharedlinkflags=['-fuse-ld=mold', '-Wl,--allow-multiple-definition']
        EOF

    - name: Add CI conan remote
      shell: bash
      run: |
        conan remote add --index=0 ci http://conanserver:9300

    - name: Install Bolt dependencies
      shell: bash
      run: |
        ./scripts/install-bolt-deps.sh
